/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CareerPathId = IDL.Nat;
export const IndustrySector = IDL.Variant({
  'healthcare' : IDL.Null,
  'finance' : IDL.Null,
  'social' : IDL.Null,
  'creative' : IDL.Null,
  'tech' : IDL.Null,
  'education' : IDL.Null,
  'engineering' : IDL.Null,
  'business' : IDL.Null,
  'science' : IDL.Null,
});
export const SalaryRange = IDL.Record({
  'max' : IDL.Nat,
  'min' : IDL.Nat,
  'currency' : IDL.Text,
});
export const CareerPath = IDL.Record({
  'id' : CareerPathId,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'sector' : IndustrySector,
  'interestTags' : IDL.Vec(IDL.Text),
  'salaryRange' : SalaryRange,
  'requiredSkills' : IDL.Vec(IDL.Text),
});
export const CareerMatch = IDL.Record({
  'matchScore' : IDL.Nat,
  'career' : CareerPath,
});
export const SkillLevel = IDL.Variant({
  'intermediate' : IDL.Null,
  'beginner' : IDL.Null,
  'advanced' : IDL.Null,
});
export const LearningStyle = IDL.Variant({
  'handson' : IDL.Null,
  'auditory' : IDL.Null,
  'readingWriting' : IDL.Null,
  'visual' : IDL.Null,
});
export const InterestCategory = IDL.Variant({
  'healthcare' : IDL.Null,
  'social' : IDL.Null,
  'arts' : IDL.Null,
  'education' : IDL.Null,
  'engineering' : IDL.Null,
  'technology' : IDL.Null,
  'business' : IDL.Null,
  'science' : IDL.Null,
});
export const UserId = IDL.Principal;
export const AssessmentAnswer = IDL.Record({
  'answer' : IDL.Text,
  'questionId' : IDL.Nat,
});
export const Timestamp = IDL.Int;
export const UserProfilePublic = IDL.Record({
  'experienceLevel' : SkillLevel,
  'learningStyle' : LearningStyle,
  'selectedCareerPathId' : IDL.Opt(CareerPathId),
  'displayName' : IDL.Text,
  'interests' : IDL.Vec(InterestCategory),
  'userId' : UserId,
  'answers' : IDL.Vec(AssessmentAnswer),
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'currentSkills' : IDL.Vec(IDL.Text),
});
export const MilestoneId = IDL.Nat;
export const UserProgress = IDL.Record({
  'startedAt' : Timestamp,
  'completedCourses' : IDL.Vec(IDL.Text),
  'userId' : UserId,
  'completedMilestones' : IDL.Vec(MilestoneId),
  'careerPathId' : CareerPathId,
  'acquiredSkills' : IDL.Vec(IDL.Text),
  'updatedAt' : Timestamp,
});
export const ProgressSummary = IDL.Record({
  'completedCount' : IDL.Nat,
  'timelineEstimate' : IDL.Text,
  'totalMilestones' : IDL.Nat,
  'nextMilestoneId' : IDL.Opt(MilestoneId),
  'careerTitle' : IDL.Text,
  'percentComplete' : IDL.Nat,
});
export const ResourceId = IDL.Nat;
export const Difficulty = IDL.Variant({
  'intermediate' : IDL.Null,
  'beginner' : IDL.Null,
  'advanced' : IDL.Null,
});
export const ResourceType = IDL.Variant({
  'video' : IDL.Null,
  'documentation' : IDL.Null,
  'article' : IDL.Null,
  'course' : IDL.Null,
});
export const LearningResource = IDL.Record({
  'id' : ResourceId,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'source' : IDL.Text,
  'difficulty' : Difficulty,
  'skillTag' : IDL.Text,
  'resourceType' : ResourceType,
  'estimatedDuration' : IDL.Text,
});
export const Milestone = IDL.Record({
  'id' : MilestoneId,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'projects' : IDL.Vec(IDL.Text),
  'careerPathId' : CareerPathId,
  'description' : IDL.Text,
  'resourceIds' : IDL.Vec(ResourceId),
  'requiredSkills' : IDL.Vec(IDL.Text),
  'estimatedTime' : IDL.Text,
});
export const SkillGap = IDL.Record({
  'missing' : IDL.Vec(IDL.Text),
  'acquired' : IDL.Vec(IDL.Text),
  'required' : IDL.Vec(IDL.Text),
});
export const SaveProfileRequest = IDL.Record({
  'experienceLevel' : SkillLevel,
  'learningStyle' : LearningStyle,
  'displayName' : IDL.Text,
  'interests' : IDL.Vec(InterestCategory),
  'answers' : IDL.Vec(AssessmentAnswer),
  'currentSkills' : IDL.Vec(IDL.Text),
});
export const ToggleMilestoneRequest = IDL.Record({
  'completed' : IDL.Bool,
  'milestoneId' : MilestoneId,
});

export const idlService = IDL.Service({
  'addAcquiredSkill' : IDL.Func([CareerPathId, IDL.Text], [], []),
  'getCareer' : IDL.Func([CareerPathId], [IDL.Opt(CareerPath)], ['query']),
  'getCareerRecommendations' : IDL.Func([], [IDL.Vec(CareerMatch)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
  'getMyProgress' : IDL.Func([], [IDL.Opt(UserProgress)], ['query']),
  'getProgressSummary' : IDL.Func([], [IDL.Opt(ProgressSummary)], ['query']),
  'getResources' : IDL.Func(
      [IDL.Vec(ResourceId)],
      [IDL.Vec(LearningResource)],
      ['query'],
    ),
  'getResourcesBySkill' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LearningResource)],
      ['query'],
    ),
  'getRoadmap' : IDL.Func([CareerPathId], [IDL.Vec(Milestone)], ['query']),
  'getSkillGap' : IDL.Func([CareerPathId], [SkillGap], ['query']),
  'listCareers' : IDL.Func([], [IDL.Vec(CareerPath)], ['query']),
  'retakeAssessment' : IDL.Func([], [], []),
  'saveMyProfile' : IDL.Func([SaveProfileRequest], [UserProfilePublic], []),
  'selectCareer' : IDL.Func([IDL.Nat], [], []),
  'toggleMilestone' : IDL.Func([ToggleMilestoneRequest], [UserProgress], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CareerPathId = IDL.Nat;
  const IndustrySector = IDL.Variant({
    'healthcare' : IDL.Null,
    'finance' : IDL.Null,
    'social' : IDL.Null,
    'creative' : IDL.Null,
    'tech' : IDL.Null,
    'education' : IDL.Null,
    'engineering' : IDL.Null,
    'business' : IDL.Null,
    'science' : IDL.Null,
  });
  const SalaryRange = IDL.Record({
    'max' : IDL.Nat,
    'min' : IDL.Nat,
    'currency' : IDL.Text,
  });
  const CareerPath = IDL.Record({
    'id' : CareerPathId,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'sector' : IndustrySector,
    'interestTags' : IDL.Vec(IDL.Text),
    'salaryRange' : SalaryRange,
    'requiredSkills' : IDL.Vec(IDL.Text),
  });
  const CareerMatch = IDL.Record({
    'matchScore' : IDL.Nat,
    'career' : CareerPath,
  });
  const SkillLevel = IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
  });
  const LearningStyle = IDL.Variant({
    'handson' : IDL.Null,
    'auditory' : IDL.Null,
    'readingWriting' : IDL.Null,
    'visual' : IDL.Null,
  });
  const InterestCategory = IDL.Variant({
    'healthcare' : IDL.Null,
    'social' : IDL.Null,
    'arts' : IDL.Null,
    'education' : IDL.Null,
    'engineering' : IDL.Null,
    'technology' : IDL.Null,
    'business' : IDL.Null,
    'science' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const AssessmentAnswer = IDL.Record({
    'answer' : IDL.Text,
    'questionId' : IDL.Nat,
  });
  const Timestamp = IDL.Int;
  const UserProfilePublic = IDL.Record({
    'experienceLevel' : SkillLevel,
    'learningStyle' : LearningStyle,
    'selectedCareerPathId' : IDL.Opt(CareerPathId),
    'displayName' : IDL.Text,
    'interests' : IDL.Vec(InterestCategory),
    'userId' : UserId,
    'answers' : IDL.Vec(AssessmentAnswer),
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'currentSkills' : IDL.Vec(IDL.Text),
  });
  const MilestoneId = IDL.Nat;
  const UserProgress = IDL.Record({
    'startedAt' : Timestamp,
    'completedCourses' : IDL.Vec(IDL.Text),
    'userId' : UserId,
    'completedMilestones' : IDL.Vec(MilestoneId),
    'careerPathId' : CareerPathId,
    'acquiredSkills' : IDL.Vec(IDL.Text),
    'updatedAt' : Timestamp,
  });
  const ProgressSummary = IDL.Record({
    'completedCount' : IDL.Nat,
    'timelineEstimate' : IDL.Text,
    'totalMilestones' : IDL.Nat,
    'nextMilestoneId' : IDL.Opt(MilestoneId),
    'careerTitle' : IDL.Text,
    'percentComplete' : IDL.Nat,
  });
  const ResourceId = IDL.Nat;
  const Difficulty = IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
  });
  const ResourceType = IDL.Variant({
    'video' : IDL.Null,
    'documentation' : IDL.Null,
    'article' : IDL.Null,
    'course' : IDL.Null,
  });
  const LearningResource = IDL.Record({
    'id' : ResourceId,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'source' : IDL.Text,
    'difficulty' : Difficulty,
    'skillTag' : IDL.Text,
    'resourceType' : ResourceType,
    'estimatedDuration' : IDL.Text,
  });
  const Milestone = IDL.Record({
    'id' : MilestoneId,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'projects' : IDL.Vec(IDL.Text),
    'careerPathId' : CareerPathId,
    'description' : IDL.Text,
    'resourceIds' : IDL.Vec(ResourceId),
    'requiredSkills' : IDL.Vec(IDL.Text),
    'estimatedTime' : IDL.Text,
  });
  const SkillGap = IDL.Record({
    'missing' : IDL.Vec(IDL.Text),
    'acquired' : IDL.Vec(IDL.Text),
    'required' : IDL.Vec(IDL.Text),
  });
  const SaveProfileRequest = IDL.Record({
    'experienceLevel' : SkillLevel,
    'learningStyle' : LearningStyle,
    'displayName' : IDL.Text,
    'interests' : IDL.Vec(InterestCategory),
    'answers' : IDL.Vec(AssessmentAnswer),
    'currentSkills' : IDL.Vec(IDL.Text),
  });
  const ToggleMilestoneRequest = IDL.Record({
    'completed' : IDL.Bool,
    'milestoneId' : MilestoneId,
  });
  
  return IDL.Service({
    'addAcquiredSkill' : IDL.Func([CareerPathId, IDL.Text], [], []),
    'getCareer' : IDL.Func([CareerPathId], [IDL.Opt(CareerPath)], ['query']),
    'getCareerRecommendations' : IDL.Func(
        [],
        [IDL.Vec(CareerMatch)],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
    'getMyProgress' : IDL.Func([], [IDL.Opt(UserProgress)], ['query']),
    'getProgressSummary' : IDL.Func([], [IDL.Opt(ProgressSummary)], ['query']),
    'getResources' : IDL.Func(
        [IDL.Vec(ResourceId)],
        [IDL.Vec(LearningResource)],
        ['query'],
      ),
    'getResourcesBySkill' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LearningResource)],
        ['query'],
      ),
    'getRoadmap' : IDL.Func([CareerPathId], [IDL.Vec(Milestone)], ['query']),
    'getSkillGap' : IDL.Func([CareerPathId], [SkillGap], ['query']),
    'listCareers' : IDL.Func([], [IDL.Vec(CareerPath)], ['query']),
    'retakeAssessment' : IDL.Func([], [], []),
    'saveMyProfile' : IDL.Func([SaveProfileRequest], [UserProfilePublic], []),
    'selectCareer' : IDL.Func([IDL.Nat], [], []),
    'toggleMilestone' : IDL.Func([ToggleMilestoneRequest], [UserProgress], []),
  });
};

export const init = ({ IDL }) => { return []; };