/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AssessmentAnswer { 'answer' : string, 'questionId' : bigint }
export interface CareerMatch { 'matchScore' : bigint, 'career' : CareerPath }
export interface CareerPath {
  'id' : CareerPathId,
  'title' : string,
  'description' : string,
  'sector' : IndustrySector,
  'interestTags' : Array<string>,
  'salaryRange' : SalaryRange,
  'requiredSkills' : Array<string>,
}
export type CareerPathId = bigint;
export type Difficulty = { 'intermediate' : null } |
  { 'beginner' : null } |
  { 'advanced' : null };
export type IndustrySector = { 'healthcare' : null } |
  { 'finance' : null } |
  { 'social' : null } |
  { 'creative' : null } |
  { 'tech' : null } |
  { 'education' : null } |
  { 'engineering' : null } |
  { 'business' : null } |
  { 'science' : null };
export type InterestCategory = { 'healthcare' : null } |
  { 'social' : null } |
  { 'arts' : null } |
  { 'education' : null } |
  { 'engineering' : null } |
  { 'technology' : null } |
  { 'business' : null } |
  { 'science' : null };
export interface LearningResource {
  'id' : ResourceId,
  'url' : string,
  'title' : string,
  'source' : string,
  'difficulty' : Difficulty,
  'skillTag' : string,
  'resourceType' : ResourceType,
  'estimatedDuration' : string,
}
export type LearningStyle = { 'handson' : null } |
  { 'auditory' : null } |
  { 'readingWriting' : null } |
  { 'visual' : null };
export interface Milestone {
  'id' : MilestoneId,
  'title' : string,
  'order' : bigint,
  'projects' : Array<string>,
  'careerPathId' : CareerPathId,
  'description' : string,
  'resourceIds' : Array<ResourceId>,
  'requiredSkills' : Array<string>,
  'estimatedTime' : string,
}
export type MilestoneId = bigint;
export interface ProgressSummary {
  'completedCount' : bigint,
  'timelineEstimate' : string,
  'totalMilestones' : bigint,
  'nextMilestoneId' : [] | [MilestoneId],
  'careerTitle' : string,
  'percentComplete' : bigint,
}
export type ResourceId = bigint;
export type ResourceType = { 'video' : null } |
  { 'documentation' : null } |
  { 'article' : null } |
  { 'course' : null };
export interface SalaryRange {
  'max' : bigint,
  'min' : bigint,
  'currency' : string,
}
export interface SaveProfileRequest {
  'experienceLevel' : SkillLevel,
  'learningStyle' : LearningStyle,
  'displayName' : string,
  'interests' : Array<InterestCategory>,
  'answers' : Array<AssessmentAnswer>,
  'currentSkills' : Array<string>,
}
export interface SkillGap {
  'missing' : Array<string>,
  'acquired' : Array<string>,
  'required' : Array<string>,
}
export type SkillLevel = { 'intermediate' : null } |
  { 'beginner' : null } |
  { 'advanced' : null };
export type Timestamp = bigint;
export interface ToggleMilestoneRequest {
  'completed' : boolean,
  'milestoneId' : MilestoneId,
}
export type UserId = Principal;
export interface UserProfilePublic {
  'experienceLevel' : SkillLevel,
  'learningStyle' : LearningStyle,
  'selectedCareerPathId' : [] | [CareerPathId],
  'displayName' : string,
  'interests' : Array<InterestCategory>,
  'userId' : UserId,
  'answers' : Array<AssessmentAnswer>,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'currentSkills' : Array<string>,
}
export interface UserProgress {
  'startedAt' : Timestamp,
  'completedCourses' : Array<string>,
  'userId' : UserId,
  'completedMilestones' : Array<MilestoneId>,
  'careerPathId' : CareerPathId,
  'acquiredSkills' : Array<string>,
  'updatedAt' : Timestamp,
}
export interface _SERVICE {
  'addAcquiredSkill' : ActorMethod<[CareerPathId, string], undefined>,
  'getCareer' : ActorMethod<[CareerPathId], [] | [CareerPath]>,
  'getCareerRecommendations' : ActorMethod<[], Array<CareerMatch>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getMyProgress' : ActorMethod<[], [] | [UserProgress]>,
  'getProgressSummary' : ActorMethod<[], [] | [ProgressSummary]>,
  'getResources' : ActorMethod<[Array<ResourceId>], Array<LearningResource>>,
  'getResourcesBySkill' : ActorMethod<[string], Array<LearningResource>>,
  'getRoadmap' : ActorMethod<[CareerPathId], Array<Milestone>>,
  'getSkillGap' : ActorMethod<[CareerPathId], SkillGap>,
  'listCareers' : ActorMethod<[], Array<CareerPath>>,
  'retakeAssessment' : ActorMethod<[], undefined>,
  'saveMyProfile' : ActorMethod<[SaveProfileRequest], UserProfilePublic>,
  'selectCareer' : ActorMethod<[bigint], undefined>,
  'toggleMilestone' : ActorMethod<[ToggleMilestoneRequest], UserProgress>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];