/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ToggleMilestoneRequest {
    completed: boolean;
    milestoneId: MilestoneId;
}
export type Timestamp = bigint;
export interface SaveProfileRequest {
    experienceLevel: SkillLevel;
    learningStyle: LearningStyle;
    displayName: string;
    interests: Array<InterestCategory>;
    answers: Array<AssessmentAnswer>;
    currentSkills: Array<string>;
}
export interface LearningResource {
    id: ResourceId;
    url: string;
    title: string;
    source: string;
    difficulty: Difficulty;
    skillTag: string;
    resourceType: ResourceType;
    estimatedDuration: string;
}
export type CareerPathId = bigint;
export interface SkillGap {
    missing: Array<string>;
    acquired: Array<string>;
    required: Array<string>;
}
export interface Milestone {
    id: MilestoneId;
    title: string;
    order: bigint;
    projects: Array<string>;
    careerPathId: CareerPathId;
    description: string;
    resourceIds: Array<ResourceId>;
    requiredSkills: Array<string>;
    estimatedTime: string;
}
export interface UserProgress {
    startedAt: Timestamp;
    completedCourses: Array<string>;
    userId: UserId;
    completedMilestones: Array<MilestoneId>;
    careerPathId: CareerPathId;
    acquiredSkills: Array<string>;
    updatedAt: Timestamp;
}
export interface UserProfilePublic {
    experienceLevel: SkillLevel;
    learningStyle: LearningStyle;
    selectedCareerPathId?: CareerPathId;
    displayName: string;
    interests: Array<InterestCategory>;
    userId: UserId;
    answers: Array<AssessmentAnswer>;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    currentSkills: Array<string>;
}
export interface CareerMatch {
    matchScore: bigint;
    career: CareerPath;
}
export type UserId = Principal;
export interface AssessmentAnswer {
    answer: string;
    questionId: bigint;
}
export type MilestoneId = bigint;
export interface CareerPath {
    id: CareerPathId;
    title: string;
    description: string;
    sector: IndustrySector;
    interestTags: Array<string>;
    salaryRange: SalaryRange;
    requiredSkills: Array<string>;
}
export type ResourceId = bigint;
export interface SalaryRange {
    max: bigint;
    min: bigint;
    currency: string;
}
export interface ProgressSummary {
    completedCount: bigint;
    timelineEstimate: string;
    totalMilestones: bigint;
    nextMilestoneId?: MilestoneId;
    careerTitle: string;
    percentComplete: bigint;
}
export enum IndustrySector {
    healthcare = "healthcare",
    finance = "finance",
    social = "social",
    creative = "creative",
    tech = "tech",
    education = "education",
    engineering = "engineering",
    business = "business",
    science = "science"
}
export enum InterestCategory {
    healthcare = "healthcare",
    social = "social",
    arts = "arts",
    education = "education",
    engineering = "engineering",
    technology = "technology",
    business = "business",
    science = "science"
}
export enum LearningStyle {
    handson = "handson",
    auditory = "auditory",
    readingWriting = "readingWriting",
    visual = "visual"
}
export enum ResourceType {
    video = "video",
    documentation = "documentation",
    article = "article",
    course = "course"
}
export enum SkillLevel {
    intermediate = "intermediate",
    beginner = "beginner",
    advanced = "advanced"
}
export interface backendInterface {
    addAcquiredSkill(careerPathId: CareerPathId, skill: string): Promise<void>;
    getCareer(id: CareerPathId): Promise<CareerPath | null>;
    getCareerRecommendations(): Promise<Array<CareerMatch>>;
    getMyProfile(): Promise<UserProfilePublic | null>;
    getMyProgress(): Promise<UserProgress | null>;
    getProgressSummary(): Promise<ProgressSummary | null>;
    getResources(ids: Array<ResourceId>): Promise<Array<LearningResource>>;
    getResourcesBySkill(skillTag: string): Promise<Array<LearningResource>>;
    getRoadmap(careerPathId: CareerPathId): Promise<Array<Milestone>>;
    getSkillGap(careerPathId: CareerPathId): Promise<SkillGap>;
    listCareers(): Promise<Array<CareerPath>>;
    retakeAssessment(): Promise<void>;
    saveMyProfile(req: SaveProfileRequest): Promise<UserProfilePublic>;
    selectCareer(careerPathId: bigint): Promise<void>;
    toggleMilestone(req: ToggleMilestoneRequest): Promise<UserProgress>;
}
import type { AssessmentAnswer as _AssessmentAnswer, CareerMatch as _CareerMatch, CareerPath as _CareerPath, CareerPathId as _CareerPathId, Difficulty as _Difficulty, IndustrySector as _IndustrySector, InterestCategory as _InterestCategory, LearningResource as _LearningResource, LearningStyle as _LearningStyle, MilestoneId as _MilestoneId, ProgressSummary as _ProgressSummary, ResourceId as _ResourceId, ResourceType as _ResourceType, SalaryRange as _SalaryRange, SaveProfileRequest as _SaveProfileRequest, SkillLevel as _SkillLevel, Timestamp as _Timestamp, UserId as _UserId, UserProfilePublic as _UserProfilePublic, UserProgress as _UserProgress } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAcquiredSkill(arg0: CareerPathId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAcquiredSkill(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAcquiredSkill(arg0, arg1);
            return result;
        }
    }
    async getCareer(arg0: CareerPathId): Promise<CareerPath | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCareer(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCareer(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCareerRecommendations(): Promise<Array<CareerMatch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCareerRecommendations();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCareerRecommendations();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProgress(): Promise<UserProgress | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProgress();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProgress();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProgressSummary(): Promise<ProgressSummary | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgressSummary();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgressSummary();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResources(arg0: Array<ResourceId>): Promise<Array<LearningResource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResources(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResources(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResourcesBySkill(arg0: string): Promise<Array<LearningResource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResourcesBySkill(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResourcesBySkill(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoadmap(arg0: CareerPathId): Promise<Array<Milestone>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoadmap(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoadmap(arg0);
            return result;
        }
    }
    async getSkillGap(arg0: CareerPathId): Promise<SkillGap> {
        if (this.processError) {
            try {
                const result = await this.actor.getSkillGap(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSkillGap(arg0);
            return result;
        }
    }
    async listCareers(): Promise<Array<CareerPath>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCareers();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCareers();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async retakeAssessment(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.retakeAssessment();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.retakeAssessment();
            return result;
        }
    }
    async saveMyProfile(arg0: SaveProfileRequest): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMyProfile(to_candid_SaveProfileRequest_n32(this._uploadFile, this._downloadFile, arg0));
                return from_candid_UserProfilePublic_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMyProfile(to_candid_SaveProfileRequest_n32(this._uploadFile, this._downloadFile, arg0));
            return from_candid_UserProfilePublic_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async selectCareer(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.selectCareer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.selectCareer(arg0);
            return result;
        }
    }
    async toggleMilestone(arg0: ToggleMilestoneRequest): Promise<UserProgress> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleMilestone(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleMilestone(arg0);
            return result;
        }
    }
}
function from_candid_CareerMatch_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CareerMatch): CareerMatch {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_CareerPath_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CareerPath): CareerPath {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Difficulty_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Difficulty): Difficulty {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_IndustrySector_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IndustrySector): IndustrySector {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_InterestCategory_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InterestCategory): InterestCategory {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_LearningResource_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LearningResource): LearningResource {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_LearningStyle_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LearningStyle): LearningStyle {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_ProgressSummary_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProgressSummary): ProgressSummary {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_ResourceType_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResourceType): ResourceType {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_SkillLevel_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SkillLevel): SkillLevel {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfilePublic_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfilePublic): UserProfilePublic {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CareerPath]): CareerPath | null {
    return value.length === 0 ? null : from_candid_CareerPath_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CareerPathId]): CareerPathId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProgress]): UserProgress | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProgressSummary]): ProgressSummary | null {
    return value.length === 0 ? null : from_candid_ProgressSummary_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MilestoneId]): MilestoneId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePublic]): UserProfilePublic | null {
    return value.length === 0 ? null : from_candid_UserProfilePublic_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    experienceLevel: _SkillLevel;
    learningStyle: _LearningStyle;
    selectedCareerPathId: [] | [_CareerPathId];
    displayName: string;
    interests: Array<_InterestCategory>;
    userId: _UserId;
    answers: Array<_AssessmentAnswer>;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
    currentSkills: Array<string>;
}): {
    experienceLevel: SkillLevel;
    learningStyle: LearningStyle;
    selectedCareerPathId?: CareerPathId;
    displayName: string;
    interests: Array<InterestCategory>;
    userId: UserId;
    answers: Array<AssessmentAnswer>;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    currentSkills: Array<string>;
} {
    return {
        experienceLevel: from_candid_SkillLevel_n12(_uploadFile, _downloadFile, value.experienceLevel),
        learningStyle: from_candid_LearningStyle_n14(_uploadFile, _downloadFile, value.learningStyle),
        selectedCareerPathId: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.selectedCareerPathId)),
        displayName: value.displayName,
        interests: from_candid_vec_n17(_uploadFile, _downloadFile, value.interests),
        userId: value.userId,
        answers: value.answers,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        currentSkills: value.currentSkills
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completedCount: bigint;
    timelineEstimate: string;
    totalMilestones: bigint;
    nextMilestoneId: [] | [_MilestoneId];
    careerTitle: string;
    percentComplete: bigint;
}): {
    completedCount: bigint;
    timelineEstimate: string;
    totalMilestones: bigint;
    nextMilestoneId?: MilestoneId;
    careerTitle: string;
    percentComplete: bigint;
} {
    return {
        completedCount: value.completedCount,
        timelineEstimate: value.timelineEstimate,
        totalMilestones: value.totalMilestones,
        nextMilestoneId: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.nextMilestoneId)),
        careerTitle: value.careerTitle,
        percentComplete: value.percentComplete
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ResourceId;
    url: string;
    title: string;
    source: string;
    difficulty: _Difficulty;
    skillTag: string;
    resourceType: _ResourceType;
    estimatedDuration: string;
}): {
    id: ResourceId;
    url: string;
    title: string;
    source: string;
    difficulty: Difficulty;
    skillTag: string;
    resourceType: ResourceType;
    estimatedDuration: string;
} {
    return {
        id: value.id,
        url: value.url,
        title: value.title,
        source: value.source,
        difficulty: from_candid_Difficulty_n28(_uploadFile, _downloadFile, value.difficulty),
        skillTag: value.skillTag,
        resourceType: from_candid_ResourceType_n29(_uploadFile, _downloadFile, value.resourceType),
        estimatedDuration: value.estimatedDuration
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CareerPathId;
    title: string;
    description: string;
    sector: _IndustrySector;
    interestTags: Array<string>;
    salaryRange: _SalaryRange;
    requiredSkills: Array<string>;
}): {
    id: CareerPathId;
    title: string;
    description: string;
    sector: IndustrySector;
    interestTags: Array<string>;
    salaryRange: SalaryRange;
    requiredSkills: Array<string>;
} {
    return {
        id: value.id,
        title: value.title,
        description: value.description,
        sector: from_candid_IndustrySector_n4(_uploadFile, _downloadFile, value.sector),
        interestTags: value.interestTags,
        salaryRange: value.salaryRange,
        requiredSkills: value.requiredSkills
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    matchScore: bigint;
    career: _CareerPath;
}): {
    matchScore: bigint;
    career: CareerPath;
} {
    return {
        matchScore: value.matchScore,
        career: from_candid_CareerPath_n2(_uploadFile, _downloadFile, value.career)
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
}): SkillLevel {
    return "intermediate" in value ? SkillLevel.intermediate : "beginner" in value ? SkillLevel.beginner : "advanced" in value ? SkillLevel.advanced : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    handson: null;
} | {
    auditory: null;
} | {
    readingWriting: null;
} | {
    visual: null;
}): LearningStyle {
    return "handson" in value ? LearningStyle.handson : "auditory" in value ? LearningStyle.auditory : "readingWriting" in value ? LearningStyle.readingWriting : "visual" in value ? LearningStyle.visual : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    healthcare: null;
} | {
    social: null;
} | {
    arts: null;
} | {
    education: null;
} | {
    engineering: null;
} | {
    technology: null;
} | {
    business: null;
} | {
    science: null;
}): InterestCategory {
    return "healthcare" in value ? InterestCategory.healthcare : "social" in value ? InterestCategory.social : "arts" in value ? InterestCategory.arts : "education" in value ? InterestCategory.education : "engineering" in value ? InterestCategory.engineering : "technology" in value ? InterestCategory.technology : "business" in value ? InterestCategory.business : "science" in value ? InterestCategory.science : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    video: null;
} | {
    documentation: null;
} | {
    article: null;
} | {
    course: null;
}): ResourceType {
    return "video" in value ? ResourceType.video : "documentation" in value ? ResourceType.documentation : "article" in value ? ResourceType.article : "course" in value ? ResourceType.course : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    healthcare: null;
} | {
    finance: null;
} | {
    social: null;
} | {
    creative: null;
} | {
    tech: null;
} | {
    education: null;
} | {
    engineering: null;
} | {
    business: null;
} | {
    science: null;
}): IndustrySector {
    return "healthcare" in value ? IndustrySector.healthcare : "finance" in value ? IndustrySector.finance : "social" in value ? IndustrySector.social : "creative" in value ? IndustrySector.creative : "tech" in value ? IndustrySector.tech : "education" in value ? IndustrySector.education : "engineering" in value ? IndustrySector.engineering : "business" in value ? IndustrySector.business : "science" in value ? IndustrySector.science : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InterestCategory>): Array<InterestCategory> {
    return value.map((x)=>from_candid_InterestCategory_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LearningResource>): Array<LearningResource> {
    return value.map((x)=>from_candid_LearningResource_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CareerPath>): Array<CareerPath> {
    return value.map((x)=>from_candid_CareerPath_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CareerMatch>): Array<CareerMatch> {
    return value.map((x)=>from_candid_CareerMatch_n7(_uploadFile, _downloadFile, x));
}
function to_candid_InterestCategory_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InterestCategory): _InterestCategory {
    return to_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function to_candid_LearningStyle_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LearningStyle): _LearningStyle {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_SaveProfileRequest_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SaveProfileRequest): _SaveProfileRequest {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_SkillLevel_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SkillLevel): _SkillLevel {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    experienceLevel: SkillLevel;
    learningStyle: LearningStyle;
    displayName: string;
    interests: Array<InterestCategory>;
    answers: Array<AssessmentAnswer>;
    currentSkills: Array<string>;
}): {
    experienceLevel: _SkillLevel;
    learningStyle: _LearningStyle;
    displayName: string;
    interests: Array<_InterestCategory>;
    answers: Array<_AssessmentAnswer>;
    currentSkills: Array<string>;
} {
    return {
        experienceLevel: to_candid_SkillLevel_n34(_uploadFile, _downloadFile, value.experienceLevel),
        learningStyle: to_candid_LearningStyle_n36(_uploadFile, _downloadFile, value.learningStyle),
        displayName: value.displayName,
        interests: to_candid_vec_n38(_uploadFile, _downloadFile, value.interests),
        answers: value.answers,
        currentSkills: value.currentSkills
    };
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SkillLevel): {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
} {
    return value == SkillLevel.intermediate ? {
        intermediate: null
    } : value == SkillLevel.beginner ? {
        beginner: null
    } : value == SkillLevel.advanced ? {
        advanced: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LearningStyle): {
    handson: null;
} | {
    auditory: null;
} | {
    readingWriting: null;
} | {
    visual: null;
} {
    return value == LearningStyle.handson ? {
        handson: null
    } : value == LearningStyle.auditory ? {
        auditory: null
    } : value == LearningStyle.readingWriting ? {
        readingWriting: null
    } : value == LearningStyle.visual ? {
        visual: null
    } : value;
}
function to_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InterestCategory): {
    healthcare: null;
} | {
    social: null;
} | {
    arts: null;
} | {
    education: null;
} | {
    engineering: null;
} | {
    technology: null;
} | {
    business: null;
} | {
    science: null;
} {
    return value == InterestCategory.healthcare ? {
        healthcare: null
    } : value == InterestCategory.social ? {
        social: null
    } : value == InterestCategory.arts ? {
        arts: null
    } : value == InterestCategory.education ? {
        education: null
    } : value == InterestCategory.engineering ? {
        engineering: null
    } : value == InterestCategory.technology ? {
        technology: null
    } : value == InterestCategory.business ? {
        business: null
    } : value == InterestCategory.science ? {
        science: null
    } : value;
}
function to_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<InterestCategory>): Array<_InterestCategory> {
    return value.map((x)=>to_candid_InterestCategory_n39(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
